# Generated by Django 2.0.7 on 2018-07-24 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='单位',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('单位', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': '单位',
                'verbose_name_plural': '单位',
            },
        ),
        migrations.CreateModel(
            name='材料',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名称', models.CharField(max_length=64)),
                ('规格', models.CharField(max_length=64)),
                ('单位', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bases.单位')),
            ],
            options={
                'verbose_name': '材料',
                'verbose_name_plural': '材料',
            },
        ),
    ]
