# Generated by Django 2.0.7 on 2018-07-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_auto_20180724_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('项目名称', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('单项工程位置', models.CharField(max_length=64)),
                ('项目名称', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.Project')),
            ],
            options={
                'verbose_name': '单项工程位置',
                'verbose_name_plural': '单项工程位置',
            },
        ),
    ]
