# Generated by Django 2.0.7 on 2018-08-03 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bases', '0003_project_subproject'),
        ('construction', '0005_auto_20180802_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('单价', models.DecimalField(decimal_places=2, max_digits=13)),
                ('图算量', models.DecimalField(decimal_places=3, max_digits=13)),
                ('金额', models.DecimalField(decimal_places=2, max_digits=13)),
                ('日期', models.DateField(auto_now=True)),
                ('入库总数量', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('入库总金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('剩余还需购买数量', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('剩余还需购买金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('制单人', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('材料', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bases.Material')),
            ],
            options={
                'verbose_name': '材料图算量',
                'verbose_name_plural': '材料图算量',
            },
        ),
    ]
