# Generated by Django 2.0.7 on 2018-08-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='金额',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
