# Generated by Django 2.0.7 on 2018-08-03 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0003_project_subproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('construction', '0007_auto_20180803_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialInRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('单号', models.CharField(max_length=64)),
                ('单价', models.DecimalField(decimal_places=2, max_digits=13)),
                ('数量', models.DecimalField(decimal_places=3, max_digits=13)),
                ('金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('日期', models.DateField()),
                ('制单人', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('材料', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bases.Material')),
            ],
            options={
                'verbose_name': '材料入库',
                'verbose_name_plural': '材料入库',
            },
        ),
        migrations.CreateModel(
            name='MaterialOutRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('单号', models.CharField(max_length=64)),
                ('平均单价', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('数量', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('日期', models.DateField()),
                ('制单人', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('材料', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bases.Material')),
            ],
            options={
                'verbose_name': '材料出库',
                'verbose_name_plural': '材料出库',
            },
        ),
        migrations.CreateModel(
            name='MaterialStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('入库数量', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('入库金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('库存数量', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('库存金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('平均单价', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('出库数量', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('出库金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('结算金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('支付金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('欠款金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('单位', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bases.Unit')),
                ('材料', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bases.Material')),
            ],
            options={
                'verbose_name': '材料汇总表',
                'verbose_name_plural': '材料汇总表',
            },
        ),
        migrations.CreateModel(
            name='MaterialCost',
            fields=[
            ],
            options={
                'verbose_name': '材料费用',
                'verbose_name_plural': '材料费用',
                'proxy': True,
                'indexes': [],
            },
            bases=('construction.materialstock',),
        ),
    ]
