# Generated by Django 2.0.7 on 2018-08-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0008_materialcost_materialinrecord_materialoutrecord_materialstock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialcost',
            options={'verbose_name': '材料费汇总', 'verbose_name_plural': '材料费汇总'},
        ),
        migrations.RemoveField(
            model_name='materialstock',
            name='单位',
        ),
    ]
