# Generated by Django 2.0.7 on 2018-08-06 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bases', '0003_project_subproject'),
        ('construction', '0009_auto_20180804_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCloseBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('结算单', models.CharField(max_length=64)),
                ('单价', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('数量', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('已支付', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('未支付', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('日期', models.DateField()),
                ('制单人', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('材料', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bases.Material')),
            ],
            options={
                'verbose_name_plural': '材料结算',
                'verbose_name': '材料结算',
            },
        ),
        migrations.CreateModel(
            name='MaterialPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('支付金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('日期', models.DateField()),
                ('制单人', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('结算单号', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='construction.MaterialCloseBill')),
            ],
            options={
                'verbose_name_plural': '材料支付',
                'verbose_name': '材料支付',
            },
        ),
        migrations.AddField(
            model_name='materialstock',
            name='未结算数量',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='materialstock',
            name='未结算金额',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='materialstock',
            name='结算数量',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='budget',
            name='单价',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='budget',
            name='图算量',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
