# Generated by Django 2.0.7 on 2018-08-06 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0010_auto_20180806_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialpay',
            old_name='结算单号',
            new_name='结算单',
        ),
    ]
