# Generated by Django 2.0.7 on 2018-08-08 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0003_project_subproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('construction', '0011_auto_20180806_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('租赁日期', models.DateField()),
                ('单价', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('数量', models.DecimalField(decimal_places=3, default=0, max_digits=13, verbose_name='单价')),
                ('制单人', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('材料设备', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bases.Material')),
            ],
            options={
                'verbose_name': '租赁租入',
                'verbose_name_plural': '租赁租入',
            },
        ),
        migrations.CreateModel(
            name='LeaseOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('归还日期', models.DateField()),
                ('数量', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('制单人', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('租赁单', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='construction.LeaseIn')),
            ],
            options={
                'verbose_name': '租赁归还',
                'verbose_name_plural': '租赁归还',
            },
        ),
        migrations.CreateModel(
            name='LeaseStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('租赁日期', models.DateField()),
                ('租赁数量', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('单价', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('归还数量', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('剩余数量', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('归还金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('结算金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('支付金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('欠款金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('材料设备', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bases.Material')),
            ],
            options={
                'verbose_name': '租赁管理',
                'verbose_name_plural': '租赁管理',
            },
        ),
        migrations.CreateModel(
            name='LeaseCost',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name': '租赁费用',
                'proxy': True,
                'verbose_name_plural': '租赁费用',
            },
            bases=('construction.leasestock',),
        ),
    ]
