# Generated by Django 2.0.7 on 2018-08-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0012_leasecost_leasein_leaseout_leasestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasein',
            name='数量',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
