# Generated by Django 2.0.7 on 2018-08-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0003_project_subproject'),
        ('construction', '0013_auto_20180808_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseout',
            name='租赁单',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='construction.LeaseStock'),
        ),
        migrations.AlterUniqueTogether(
            name='leasein',
            unique_together={('租赁日期', '材料设备', '单价')},
        ),
        migrations.AlterUniqueTogether(
            name='leasestock',
            unique_together={('材料设备', '租赁日期', '单价')},
        ),
    ]
