# Generated by Django 2.0.7 on 2018-08-09 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('construction', '0016_auto_20180808_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborCloseBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('结算单号', models.CharField(max_length=64)),
                ('结算时间', models.DateField()),
                ('结算金额', models.DecimalField(decimal_places=2, max_digits=13)),
                ('支付金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('欠款金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('备注', models.CharField(blank=True, max_length=256, null=True)),
                ('制单人', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '人工费用结算',
                'verbose_name': '人工费用结算',
            },
        ),
        migrations.CreateModel(
            name='LaborCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('项目', models.CharField(max_length=64)),
                ('累计结算金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('累计支付金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('欠款金额', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('制单人', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '人工费总表',
                'verbose_name': '人工费总表',
            },
        ),
        migrations.CreateModel(
            name='LaborPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('支付时间', models.DateField()),
                ('支付金额', models.DecimalField(decimal_places=2, max_digits=13)),
                ('制单人', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('结算单号', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.LaborCloseBill')),
                ('项目', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='construction.LaborCost')),
            ],
            options={
                'verbose_name_plural': '人工费用支付',
                'verbose_name': '人工费用支付',
            },
        ),
        migrations.AddField(
            model_name='laborclosebill',
            name='项目',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='construction.LaborCost'),
        ),
    ]
